[repository]
name = "sc-videos"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/simplesconsultoria/sc-videos"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "sc.videos"
path = "backend"
code_path = "src/sc/videos"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@simplesconsultoria/volto-videos"
path = "frontend/packages/volto-videos"
code_path = "src"
changelog = "frontend/packages/volto-videos/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-videos/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "c0e9ef026f714e960832e00129c0ac2bcd0385f5"
generated_date = "2026-04-10 19:06:35"
